apiVersion: v1
kind: Secret
metadata:
  name: market-secrets
  namespace: market
type: Opaque
stringData:
  BASE_URL: "http://localhost:8090"
  BASE_ADMIN_EMAIL: "z@hanzo.ai"
  BASE_ADMIN_PASSWORD: "CHANGE_ME"
  IAM_CLIENT_ID: "app-market"
  IAM_CLIENT_SECRET: "CHANGE_ME"
  S3_ACCESS_KEY: "hanzo"
  S3_SECRET_KEY: "CHANGE_ME"
  OPENAI_API_KEY: "CHANGE_ME"
